### ISSUE TITLE
npm install fails 

### ISSUE THREAD

**Issue by ksXV** [RyanFitzgerald/devportfolio#145]
i cloned this project and ran 'npm install' but gulp-sass gives this error.
```
3477 timing build:run:postinstall:node_modules/es5-ext Completed in 396ms
3478 info run node-sass@4.14.1 postinstall { code: 1, signal: null }
3479 timing reify:rollback:createSparse Completed in 2270ms
3480 timing reify:rollback:retireShallow Completed in 0ms
3481 timing command:i Completed in 131897ms
3482 verbose stack Error: command failed
3482 verbose stack     at ChildProcess.<anonymous> (C:\Users\Name\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
3482 verbose stack     at ChildProcess.emit (node:events:390:28)
3482 verbose stack     at maybeClose (node:internal/child_process:1064:16)
3482 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
3483 verbose pkgid node-sass@4.14.1
3484 verbose cwd D:\projects\devportfolio
3485 verbose Windows_NT 10.0.19044
3486 verbose node v16.13.1
3487 verbose npm  v8.12.1
3488 error code 1
3489 error path D:\projects\devportfolio\node_modules\node-sass
3490 error command failed
3491 error command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
3492 error Building: C:\Program Files\nodejs\node.exe D:\projects\devportfolio\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
3493 error gyp info it worked if it ends with ok
3493 error gyp verb cli [
3493 error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
3493 error gyp verb cli   'D:\\projects\\devportfolio\\node_modules\\node-gyp\\bin\\node-gyp.js',
3493 error gyp verb cli   'rebuild',
3493 error gyp verb cli   '--verbose',
3493 error gyp verb cli   '--libsass_ext=',
3493 error gyp verb cli   '--libsass_cflags=',
3493 error gyp verb cli   '--libsass_ldflags=',
3493 error gyp verb cli   '--libsass_library='
3493 error gyp verb cli ]
3493 error gyp info using node-gyp@3.8.0
3493 error gyp info using node@16.13.1 | win32 | x64
3493 error gyp verb command rebuild []
3493 error gyp verb command clean []
3493 error gyp verb clean removing "build" directory
3493 error gyp verb command configure []
3493 error gyp verb check python checking for Python executable "python2" in the PATH
3493 error gyp verb `which` failed Error: not found: python2
3493 error gyp verb `which` failed     at getNotFoundError (D:\projects\devportfolio\node_modules\which\which.js:13:12)
3493 error gyp verb `which` failed     at F (D:\projects\devportfolio\node_modules\which\which.js:68:19)
3493 error gyp verb `which` failed     at E (D:\projects\devportfolio\node_modules\which\which.js:80:29)
3493 error gyp verb `which` failed     at D:\projects\devportfolio\node_modules\which\which.js:89:16
3493 error gyp verb `which` failed     at D:\projects\devportfolio\node_modules\isexe\index.js:42:5
3493 error gyp verb `which` failed     at D:\projects\devportfolio\node_modules\isexe\windows.js:36:5
3493 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
3493 error gyp verb `which` failed  python2 Error: not found: python2
3493 error gyp verb `which` failed     at getNotFoundError (D:\projects\devportfolio\node_modules\which\which.js:13:12)
3493 error gyp verb `which` failed     at F (D:\projects\devportfolio\node_modules\which\which.js:68:19)
3493 error gyp verb `which` failed     at E (D:\projects\devportfolio\node_modules\which\which.js:80:29)
3493 error gyp verb `which` failed     at D:\projects\devportfolio\node_modules\which\which.js:89:16
3493 error gyp verb `which` failed     at D:\projects\devportfolio\node_modules\isexe\index.js:42:5
3493 error gyp verb `which` failed     at D:\projects\devportfolio\node_modules\isexe\windows.js:36:5
3493 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
3493 error gyp verb `which` failed   code: 'ENOENT'
3493 error gyp verb `which` failed }
3493 error gyp verb check python checking for Python executable "python" in the PATH
3493 error gyp verb `which` succeeded python C:\Python39\python.EXE
3493 error gyp ERR! configure error 
3493 error gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
3493 error gyp ERR! stack   File "<string>", line 1
3493 error gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
3493 error gyp ERR! stack                       ^
3493 error gyp ERR! stack SyntaxError: invalid syntax
3493 error gyp ERR! stack 
3493 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
3493 error gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
3493 error gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
3493 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
3493 error gyp ERR! System Windows_NT 10.0.19044
3493 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\projects\\devportfolio\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
3493 error gyp ERR! cwd D:\projects\devportfolio\node_modules\node-sass
3493 error gyp ERR! node -v v16.13.1
3493 error gyp ERR! node-gyp -v v3.8.0
3493 error gyp ERR! not ok 
3493 error Build failed with error code: 1
3494 verbose exit 1
3495 timing npm Completed in 134349ms
3496 verbose unfinished npm timer reify 1655718519663
3497 verbose unfinished npm timer reify:build 1655718644390
3498 verbose unfinished npm timer build 1655718644393
3499 verbose unfinished npm timer build:deps 1655718644395
3500 verbose unfinished npm timer build:run:postinstall 1655718645611
3501 verbose unfinished npm timer build:run:postinstall:node_modules/node-sass 1655718645863
3502 verbose code 1```

**Comment by felix-yuxiang** [comment]
I tried `nvm install 13` (using Node13) and it helped me bypass this issue

**Comment by bharadwaj-chukkala** [comment]
doesn't work for me. I am facing the same issue. Please help
